# Stat 133 Assignment 8
Xinyang Geng

In [3]:
library(DataComputing)

In [4]:
address <- readRDS("address.rds")

In [5]:
head(address)

                     address first_name sex
1               900 SETON DR    ARDALAN   M
2             2650 RIDGE AVE     THOMAS   M
3 4126 N HOLLAND SYLVANIA RD     RASHID   M
4              456 MAGEE AVE      DAVID   M
5           11100 EUCLID AVE   JENNIFER   F
6           12605 E 16TH AVE      KEVIN   M

In [6]:
sampled_address = address %>%
    sample_n(size=50)
sampled_address

                              address first_name sex
223518                3401 N BROAD ST       PAUL   M
790732             1515 HOLCOMBE BLVD   JENNIFER   F
362540                 171 ASHLEY AVE    PHILLIP   M
575045               185 ROSEBERRY ST    RODOLFO   M
120413               3133 S SENECA ST        TED   M
151813            330 MOUNT AUBURN ST      SUSAN   F
654607                   1900 PINE ST      DAVID   M
464995                 2037 OCEAN AVE    JEFFREY   M
381557            2410 S STEMMONS FWY     BRENDA   F
874006               415 N 8TH STREET  JOSEPHINE   F
235147        W129N7055 NORTHFIELD DR      BRETT   M
856492                 90 CONCORD AVE    DEBORAH   F
554646     9601 INTERSTATE 630 EXIT 7    MICHAEL   M
660905                  30 CHOCTAW ST      JAMES   M
903342                12303 DEPAUL DR     ROBERT   M
450828               3525 E LOUISE DR     ARNOLD   M
407704                 700 WEST AVE S    MICHAEL   M
347887            5950 UNIVERSITY AVE      JAMES   M
320935            125 PARKER HILL AVE      DAVID   M
123108               17000 HUBBARD DR         HI   M
792885               4203 CLOVER LEAF
687550 2100 MARTIN LUTHER KING JR WAY
749044               3819 TWEEDY BLVD
665405         1700 HOSPITAL SOUTH DR       MINA   M
872517            1501 N CAMPBELL AVE     STEVEN   M
74527               1520 SAN PABLO ST  ALEXANDER   M
39278                  201 POPLAR AVE    CIPRIAN   M
758595            348 BROWN'S HILL CT   MEREDITH   F
173951                 1924 ALCOA HWY       JOHN   M
552715               717 E REZANOF DR      WELBY   M
300760           44633 JOY RD STE 100     JEROME   M
367657             3201 NE SKYLINE DR     JEWELL   F
789219        7750 S BROADWAY STE G20      DEBRA   F
496327    2800 BAHIA VISTA ST STE 300       GARY   M
506825               1799 DEKALB PIKE
133608                 101 ELM AVE SE      BRIAN   M
705771                   325B KING ST    STEPHEN   M
502348                  2525 N 8TH ST    WILLIAM   M
609961              3901 RAINBOW BLVD       CARY   F
122743                 1230 AMELIA ST    STEPHEN   M
268206           825 OLD LANCASTER RD   ROCHELLE   F
805116              116 S PALISADE DR       MARY   F
876439                 320 POMFRET ST    COLLEEN   F
763099                 600 N WOLFE ST    ALLISON   F
668529               105 THORNHILL DR     SAMUEL   M
645734           650 KOMAS DRIVE #200   PATRICIA   F
582228                655 E CEDAR AVE      SARAH   F
84746         1026 W 11 MILE RD STE B    JEFFREY   M
575447               613 ELIZABETH ST         C.   M
260536               2825 PARKLAWN DR    LEONARD   M

## Testing Regex

#### 1.
Pattern like \[number\] \[name\] \[street\]

In [9]:
# Match
sampled_address %>%
    filter(grepl("[0-9]+ [A-Z]+ ST", address))

              address first_name sex
1    185 ROSEBERRY ST    RODOLFO   M
2        1900 PINE ST      DAVID   M
3 2410 S STEMMONS FWY     BRENDA   F
4       30 CHOCTAW ST      JAMES   M
5      1230 AMELIA ST    STEPHEN   M
6      320 POMFRET ST    COLLEEN   F
7    613 ELIZABETH ST         C.   M

In [10]:
# Not match
sampled_address %>%
    filter(!grepl("[0-9]+ [A-Z]+ ST", address))

                          address first_name sex
1                 3401 N BROAD ST       PAUL   M
2              1515 HOLCOMBE BLVD   JENNIFER   F
3                  171 ASHLEY AVE    PHILLIP   M
4                3133 S SENECA ST        TED   M
5             330 MOUNT AUBURN ST      SUSAN   F
6                  2037 OCEAN AVE    JEFFREY   M
7                415 N 8TH STREET  JOSEPHINE   F
8         W129N7055 NORTHFIELD DR      BRETT   M
9                  90 CONCORD AVE    DEBORAH   F
10     9601 INTERSTATE 630 EXIT 7    MICHAEL   M
11                12303 DEPAUL DR     ROBERT   M
12               3525 E LOUISE DR     ARNOLD   M
13                 700 WEST AVE S    MICHAEL   M
14            5950 UNIVERSITY AVE      JAMES   M
15            125 PARKER HILL AVE      DAVID   M
16               17000 HUBBARD DR         HI   M
17               4203 CLOVER LEAF
18 2100 MARTIN LUTHER KING JR WAY
19               3819 TWEEDY BLVD
20         1700 HOSPITAL SOUTH DR       MINA   M
21            1501 N CAMPBELL AVE     STEVEN   M
22              1520 SAN PABLO ST  ALEXANDER   M
23                 201 POPLAR AVE    CIPRIAN   M
24            348 BROWN'S HILL CT   MEREDITH   F
25                 1924 ALCOA HWY       JOHN   M
26               717 E REZANOF DR      WELBY   M
27           44633 JOY RD STE 100     JEROME   M
28             3201 NE SKYLINE DR     JEWELL   F
29        7750 S BROADWAY STE G20      DEBRA   F
30    2800 BAHIA VISTA ST STE 300       GARY   M
31               1799 DEKALB PIKE
32                 101 ELM AVE SE      BRIAN   M
33                   325B KING ST    STEPHEN   M
34                  2525 N 8TH ST    WILLIAM   M
35              3901 RAINBOW BLVD       CARY   F
36           825 OLD LANCASTER RD   ROCHELLE   F
37              116 S PALISADE DR       MARY   F
38                 600 N WOLFE ST    ALLISON   F
39               105 THORNHILL DR     SAMUEL   M
40           650 KOMAS DRIVE #200   PATRICIA   F
41                655 E CEDAR AVE      SARAH   F
42        1026 W 11 MILE RD STE B    JEFFREY   M
43               2825 PARKLAWN DR    LEONARD   M

#### 2.
Pattern like \[number\] th street

In [14]:
# Match
sampled_address %>%
    filter(grepl("[0-9]+ [A-Z]+ ST", address))

           address first_name sex
1 415 N 8TH STREET  JOSEPHINE   F
2    2525 N 8TH ST    WILLIAM   M

In [15]:
# Not match
sampled_address %>%
    filter(!grepl("[0-9]+ [A-Z]+ ST", address))

                          address first_name sex
1                 3401 N BROAD ST       PAUL   M
2              1515 HOLCOMBE BLVD   JENNIFER   F
3                  171 ASHLEY AVE    PHILLIP   M
4                3133 S SENECA ST        TED   M
5             330 MOUNT AUBURN ST      SUSAN   F
6                  2037 OCEAN AVE    JEFFREY   M
7                415 N 8TH STREET  JOSEPHINE   F
8         W129N7055 NORTHFIELD DR      BRETT   M
9                  90 CONCORD AVE    DEBORAH   F
10     9601 INTERSTATE 630 EXIT 7    MICHAEL   M
11                12303 DEPAUL DR     ROBERT   M
12               3525 E LOUISE DR     ARNOLD   M
13                 700 WEST AVE S    MICHAEL   M
14            5950 UNIVERSITY AVE      JAMES   M
15            125 PARKER HILL AVE      DAVID   M
16               17000 HUBBARD DR         HI   M
17               4203 CLOVER LEAF
18 2100 MARTIN LUTHER KING JR WAY
19               3819 TWEEDY BLVD
20         1700 HOSPITAL SOUTH DR       MINA   M
21            1501 N CAMPBELL AVE     STEVEN   M
22              1520 SAN PABLO ST  ALEXANDER   M
23                 201 POPLAR AVE    CIPRIAN   M
24            348 BROWN'S HILL CT   MEREDITH   F
25                 1924 ALCOA HWY       JOHN   M
26               717 E REZANOF DR      WELBY   M
27           44633 JOY RD STE 100     JEROME   M
28             3201 NE SKYLINE DR     JEWELL   F
29        7750 S BROADWAY STE G20      DEBRA   F
30    2800 BAHIA VISTA ST STE 300       GARY   M
31               1799 DEKALB PIKE
32                 101 ELM AVE SE      BRIAN   M
33                   325B KING ST    STEPHEN   M
34                  2525 N 8TH ST    WILLIAM   M
35              3901 RAINBOW BLVD       CARY   F
36           825 OLD LANCASTER RD   ROCHELLE   F
37              116 S PALISADE DR       MARY   F
38                 600 N WOLFE ST    ALLISON   F
39               105 THORNHILL DR     SAMUEL   M
40           650 KOMAS DRIVE #200   PATRICIA   F
41                655 E CEDAR AVE      SARAH   F
42        1026 W 11 MILE RD STE B    JEFFREY   M
43               2825 PARKLAWN DR    LEONARD   M

In [17]:
pattern <- "(ST|RD|ROAD)"
sampled_address %>% 
    filter(!grepl(pattern, address),  # Not contain ST, RD or ROAD
           !grepl(" APT|UNIT [[:digit:]]+$", address)) 
            # Not contain APT or UNIT followed by a space, numbers in the end of the string.

                          address first_name sex
1              1515 HOLCOMBE BLVD   JENNIFER   F
2                  171 ASHLEY AVE    PHILLIP   M
3                  2037 OCEAN AVE    JEFFREY   M
4         W129N7055 NORTHFIELD DR      BRETT   M
5                 12303 DEPAUL DR     ROBERT   M
6                3525 E LOUISE DR     ARNOLD   M
7             5950 UNIVERSITY AVE      JAMES   M
8             125 PARKER HILL AVE      DAVID   M
9                4203 CLOVER LEAF
10 2100 MARTIN LUTHER KING JR WAY
11               3819 TWEEDY BLVD
12         1700 HOSPITAL SOUTH DR       MINA   M
13            1501 N CAMPBELL AVE     STEVEN   M
14                 201 POPLAR AVE    CIPRIAN   M
15            348 BROWN'S HILL CT   MEREDITH   F
16                 1924 ALCOA HWY       JOHN   M
17               717 E REZANOF DR      WELBY   M
18             3201 NE SKYLINE DR     JEWELL   F
19               1799 DEKALB PIKE
20                 101 ELM AVE SE      BRIAN   M
21              3901 RAINBOW BLVD       CARY   F
22              116 S PALISADE DR       MARY   F
23               105 THORNHILL DR     SAMUEL   M
24           650 KOMAS DRIVE #200   PATRICIA   F
25                655 E CEDAR AVE      SARAH   F
26               2825 PARKLAWN DR    LEONARD   M